import { StyleSheet } from 'react-native';
import { Colors } from "../../theme/colors";
import { scale } from '../../utils/normalizeSize';

const DataStyles = StyleSheet.create({
  sectionTitle: {
    fontSize: scale.hp(2.1),
    marginBottom: scale.hp(1.55),
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  smallLabel: {
    fontSize: scale.hp(1.7),
    color: Colors.textPrimary,
    marginBottom: scale.hp(0.8),
    marginTop: scale.hp(1.55),
  },
  dropField: {
    height: scale.hp(8.4),
    borderRadius: scale.hp(6.5),
    marginBottom: scale.hp(1.95),
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: scale.wp(3.9),
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: scale.hp(1.05),
    marginBottom: scale.hp(1.55),
  },
  editLink: {
    color: Colors.primary,
    fontSize: scale.hp(2.1),
    fontWeight: "600",
  },
  phoneRow: {
    flexDirection: "row",
    height: scale.hp(8.4),
    borderRadius: scale.hp(6.5),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E6E6E6",
    backgroundColor: "#fff",
  },
  phonePrefix: {
    paddingHorizontal: scale.wp(3.9),
    flexDirection: "row",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#EEE",
    backgroundColor: "#FAFAFA",
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: scale.wp(3.9),
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
  },
  operatorPill: {
    alignSelf: "flex-start",
    paddingHorizontal: scale.wp(2.4),
    height: scale.hp(3.1),
    borderRadius: scale.hp(1.55),
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  countryBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.05),
    paddingHorizontal: scale.wp(3.9),
    backgroundColor: "#F5F5F5",
    borderRadius: scale.hp(2.6),
    alignSelf: "flex-start",
    marginBottom: scale.hp(2.1),
  },
  categoriesScroll: {
    marginBottom: scale.hp(2.1),
  },
  categoriesContainer: {
    flexDirection: "row",
    gap: scale.wp(1.95),
  },
  categoryChip: {
    paddingHorizontal: scale.wp(4.9),
    paddingVertical: scale.hp(1.55),
    borderRadius: scale.hp(3.2),
    backgroundColor: "#F5F5F5",
  },
  categoryChipActive: {
    backgroundColor: Colors.primary,
  },
  categoryText: {
    fontSize: scale.hp(1.8),
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  categoryTextActive: {
    color: Colors.white,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: scale.hp(6.5),
    paddingHorizontal: scale.wp(3.9),
    marginBottom: scale.hp(2.1),
    height: scale.hp(6.5),
  },
  searchIcon: {
    marginRight: scale.wp(2),
  },
  searchInput: {
    flex: 1,
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
  },
  bundleCard: {
    borderRadius: scale.hp(2.1),
    borderWidth: 1,
    borderColor: "#E8E8E8",
    backgroundColor: "#fff",
    padding: scale.hp(2.1),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  bundleCardActive: {
    borderColor: Colors.primary,
    backgroundColor: "#FFF5F5",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  bundleHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  operatorLogo: {
    width: scale.wp(9.75),
    height: scale.wp(9.75),
    borderRadius: scale.wp(4.9),
    marginRight: scale.wp(2.9),
  },
  bundleInfo: {
    flex: 1,
  },
  bundleName: {
    fontSize: scale.hp(2.1),
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: scale.hp(0.5),
  },
  bundleDesc: {
    fontSize: scale.hp(1.8),
    color: Colors.textSecondary,
    lineHeight: scale.hp(2.6),
  },
  bundleFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bundlePrice: {
    fontSize: scale.hp(2.35),
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  bundleSeparator: {
    height: scale.hp(1.55),
  },
  summaryCard: {
    marginTop: scale.hp(2.35),
    borderWidth: 1,
    borderColor: "#F2DAD7",
    backgroundColor: "#FFF",
    borderRadius: scale.hp(1.55),
    padding: scale.hp(2.1),
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: scale.hp(0.8),
  },
  summaryTotal: {
    borderTopWidth: 1,
    borderTopColor: "#F2F2F2",
    paddingTop: scale.hp(1.05),
    marginTop: scale.hp(0.5),
  },
  summaryKey: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.8),
  },
  summaryValue: {
    color: Colors.textPrimary,
    fontSize: scale.hp(1.8),
    textAlign: "right",
    flex: 1,
    paddingLeft: scale.wp(2),
  },
  successCircle: {
    width: scale.wp(23.4),
    height: scale.wp(23.4),
    borderRadius: scale.wp(11.7),
    backgroundColor: "rgba(76,175,80,0.1)",
    borderWidth: 2,
    borderColor: "rgba(76,175,80,0.35)",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: scale.hp(1.55),
  },
  successTitle: {
    fontSize: scale.hp(2.6),
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: scale.hp(2.1),
  },
  kv: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: scale.hp(0.8),
  },
  k: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.7),
  },
  v: {
    color: Colors.textPrimary,
    fontSize: scale.hp(1.7),
  },
  totalBox: {
    width: "100%",
    backgroundColor: "#F5F5F7",
    borderRadius: scale.hp(1.55),
    paddingVertical: scale.hp(1.8),
    alignItems: "center",
    marginVertical: scale.hp(2.35),
  },
  totalLabel: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.55),
  },
  totalValue: {
    color: Colors.textPrimary,
    fontSize: scale.hp(2.6),
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: scale.hp(3.2),
    borderTopRightRadius: scale.hp(3.2),
    padding: scale.hp(2.1),
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scale.hp(2.1),
    paddingBottom: scale.hp(1.55),
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  modalTitle: {
    fontSize: scale.hp(2.35),
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  modalRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.55),
    paddingHorizontal: scale.wp(2),
  },
  closeButton: {
    padding: scale.hp(0.5),
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: scale.hp(5.2),
  },
  emptyText: {
    fontSize: scale.hp(2.1),
    color: "#999",
    marginTop: scale.hp(1.55),
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.55),
  },
  contactAvatar: {
    width: scale.wp(9.75),
    height: scale.wp(9.75),
    borderRadius: scale.wp(4.9),
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: scale.wp(2.9),
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: scale.hp(2.1),
    fontWeight: "500",
    color: Colors.textPrimary,
  },
  contactPhone: {
    fontSize: scale.hp(1.8),
    color: Colors.textSecondary,
    marginTop: scale.hp(0.25),
  },
  contactSeparator: {
    height: 1,
    backgroundColor: "#F0F0F0",
  },
  emptyProducts: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: scale.hp(5.2),
  },
  emptyProductsText: {
    fontSize: scale.hp(2.1),
    color: "#999",
    marginTop: scale.hp(1.55),
  },
  activeFiltersContainer: {
    backgroundColor: '#F8F9FA',
    padding: scale.hp(1.55),
    borderRadius: scale.hp(1.0),
    marginBottom: scale.hp(1.55),
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
  },
  activeFiltersText: {
    fontSize: scale.hp(1.7),
    color: Colors.textSecondary,
    marginBottom: scale.hp(0.8),
    fontWeight: '600',
  },
  activeFiltersChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  activeFilterChip: {
    backgroundColor: Colors.primary + '20',
    paddingHorizontal: scale.wp(2.4),
    paddingVertical: scale.hp(0.5),
    borderRadius: scale.hp(1.0),
    marginRight: scale.wp(1.5),
    marginBottom: scale.hp(0.5),
  },
  activeFilterText: {
    fontSize: scale.hp(1.5),
    color: Colors.primary,
    fontWeight: '500',
  },
  clearFiltersButton: {
    marginTop: scale.hp(1.55),
    padding: scale.hp(1.05),
    backgroundColor: Colors.primary,
    borderRadius: scale.hp(1.0),
    alignItems: 'center',
  },
  clearFiltersText: {
    color: Colors.white,
    fontSize: scale.hp(1.7),
    fontWeight: '600',
  },
    statusHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  statusIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    marginBottom: 16,
  },
  statusTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  lottieAnimation: {
    width: 80,
    height: 80,
  },
  detailsCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  detailLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  amountSection: {
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: '#f0f0f0',
  },
  amountLabel: {
    fontSize: 16,
    color: '#666',
    marginBottom: 8,
  },
  amountValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  statusMessageContainer: {
    backgroundColor: '#f8f9fa',
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
    width: '100%',
  },
  statusMessage: {
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 22,
  },
  progressContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 20,
  },
  progressBar: {
    width: '100%',
    height: 6,
    backgroundColor: '#e9ecef',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  progressText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  moreButton: {
    marginTop: 16,
    paddingVertical: 12,
  },
  moreButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Modal Styles (if not already present)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopLeftRadius: scale.hp(2.5),
    borderTopRightRadius: scale.hp(2.5),
    paddingTop: scale.hp(2),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale.wp(5),
    paddingBottom: scale.hp(2),
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitle: {
    fontSize: scale.hp(2.25),
    fontWeight: '600',
    color: '#1F2937',
  },
  closeButton: {
    padding: scale.hp(0.5),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    margin: scale.wp(5),
    marginTop: scale.hp(2),
    paddingHorizontal: scale.wp(4),
    borderRadius: scale.hp(1.5),
    height: scale.hp(6),
  },
  searchIcon: {
    marginRight: scale.wp(3),
  },
  searchInput: {
    flex: 1,
    fontSize: scale.hp(2),
    color: '#1F2937',
    height: '100%',
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale.wp(5),
    paddingVertical: scale.hp(1.5),
  },
  contactAvatar: {
    width: scale.wp(10),
    height: scale.wp(10),
    borderRadius: scale.wp(5),
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale.wp(3),
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: scale.hp(2),
    fontWeight: '500',
    color: '#1F2937',
    marginBottom: scale.hp(0.25),
  },
  contactPhone: {
    fontSize: scale.hp(1.75),
    color: '#6B7280',
  },
  contactSeparator: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginLeft: scale.wp(18),
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale.hp(7.5),
  },
  emptyText: {
    marginTop: scale.hp(1.5),
    fontSize: scale.hp(2),
    color: '#6B7280',
  },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale.wp(5),
    paddingVertical: scale.hp(2),
  },
});

export default DataStyles;