import { StyleSheet } from "react-native";
import { Colors } from "../../theme/colors";
import { scale } from "../../utils/normalizeSize";

const OrderStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    marginBottom: scale.hp(14.2),
  },
  listContainer: {
    padding: scale.hp(2.1),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: scale.hp(2.1),
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  receiptModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  header1: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
  },
  DownloadBut: {
    padding: scale.hp(0.9),
    borderRadius: scale.hp(1.8),
    backgroundColor: "#F3F4F6",
  },
  ShareBut: {
    padding: scale.hp(0.9),
    borderRadius: scale.hp(1.8),
    backgroundColor: "#F3F4F6",
  },
  headerButton: {
    display: "flex",
    flexDirection: "row",
    gap: scale.wp(2.6),
    justifyContent: "space-between",
  },
  receiptModalContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: scale.hp(1.3),
    },
    shadowOpacity: 0.3,
    shadowRadius: scale.hp(2.6),
    elevation: 10,
  },
  receiptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale.wp(4.9),
    paddingVertical: scale.hp(2.1),
    backgroundColor: Colors.primary,
    borderTopLeftRadius: scale.hp(3.1),
    borderTopRightRadius: scale.hp(3.1),
  },
  receiptHeaderLeft: {
    flex: 1,
  },
  receiptHeaderCenter: {
    flex: 2,
    alignItems: 'center',
  },
  receiptHeaderRight: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  receiptCloseButton: {
    width: scale.wp(7.8),
    height: scale.wp(7.8),
    borderRadius: scale.wp(3.9),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptHeaderActionButton: {
    width: scale.wp(8.8),
    height: scale.wp(8.8),
    borderRadius: scale.wp(4.4),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: scale.wp(2),
  },
  receiptTitle: {
    fontSize: scale.hp(2.35),
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  receiptContent: {
    flex: 1,
    padding: scale.hp(2.6),
  },
  receiptStatusSection: {
    alignItems: 'center',
    marginBottom: scale.hp(1.55),
  },
  receiptStatusIconContainer: {
    width: scale.wp(24.3),
    height: scale.wp(24.3),
    borderRadius: scale.wp(24.3),
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptTopSection: {
    alignItems: 'center',
  },
  receiptAmountValueTop: {
    fontSize: scale.hp(3.1),
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: scale.hp(3.1),
    color: Colors.textPrimary,
  },
  receiptDetailsGrid: {
    marginBottom: scale.hp(3.1),
  },
  receiptDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: scale.hp(1.55),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  receiptDetailLabel: {
    fontSize: scale.hp(1.8),
    color: '#6B7280',
    flex: 1,
  },
  receiptDetailValue: {
    fontSize: scale.hp(1.8),
    fontWeight: '500',
    color: Colors.textPrimary,
    flex: 1,
    textAlign: 'right',
  },
  receiptAmountSection: {
    alignItems: 'center',
    marginBottom: scale.hp(3.1),
    backgroundColor: '#F3F4F6',
    borderRadius: scale.hp(1.55),
    padding: scale.hp(2.1),
  },
  receiptAmountLabel: {
    fontSize: scale.hp(1.8),
    color: '#6B7280',
    marginBottom: scale.hp(0.5),
  },
  receiptAmountValue: {
    fontSize: scale.hp(3.1),
    fontWeight: 'bold',
    color: Colors.textPrimary,
  },
  receiptAdditionalInfo: {
    backgroundColor: '#F9FAFB',
    borderRadius: scale.hp(1.55),
    padding: scale.hp(2.1),
    marginBottom: scale.hp(3.1),
  },
  receiptInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale.hp(1.05),
  },
  receiptInfoText: {
    fontSize: scale.hp(1.55),
    color: '#6B7280',
    marginLeft: scale.wp(2),
    flex: 1,
  },
  receiptActions: {
    padding: scale.hp(5.2),
    paddingHorizontal: scale.wp(4.9),
    paddingTop: 0,
    gap: scale.hp(1.55),
  },
  receiptPrimaryButton: {
    backgroundColor: Colors.primary,
    paddingVertical: scale.hp(1.8),
    paddingHorizontal: scale.wp(5.8),
    borderRadius: scale.hp(13),
    width: "100%",
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptPrimaryButtonText: {
    color: '#fff',
    fontSize: scale.hp(2.1),
    fontWeight: '600',
  },
  receiptShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale.hp(1.8),
    paddingHorizontal: scale.wp(5.8),
    borderRadius: scale.hp(1.55),
    width: "100%",
    borderWidth: 1,
    borderColor: Colors.primary,
    backgroundColor: 'transparent',
  },
  receiptShareButtonText: {
    color: Colors.primary,
    fontSize: scale.hp(2.1),
    fontWeight: '600',
    marginLeft: scale.wp(2),
  },
  headerTitle: {
    fontSize: scale.hp(2.6),
    fontWeight: 'bold',
    color: '#333',
  },
  filterButton: {
    padding: scale.hp(0.5),
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: scale.hp(2.1),
    borderRadius: scale.hp(1.05),
    paddingHorizontal: scale.wp(2.9),
    borderWidth: 1,
    borderColor: '#ddd',
  },
  searchIcon: {
    marginRight: scale.wp(2),
  },
  searchInput: {
    flex: 1,
    height: scale.hp(5.7),
    fontSize: scale.hp(2.1),
  },

 orderItem: {
  backgroundColor: '#fff',
  borderRadius: scale.hp(1.55),
  padding: scale.hp(2.1),
  marginBottom: scale.hp(2.1),
  shadowColor: '#000',
  shadowOffset: { width: 0, height: scale.hp(0.25) },
  shadowOpacity: 0.1,
  shadowRadius: scale.hp(0.5),
  elevation: 3,
  borderLeftWidth: 4,
  borderLeftColor: Colors.primary,
},
orderHeader: {
  marginBottom: scale.hp(1.55),
},
orderIdContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: scale.hp(1.05),
},
txnId: {
  fontSize: scale.hp(1.8),
  fontWeight: '600',
  color: '#333',
  flex: 1,
},
statusBadge: {
  paddingHorizontal: scale.wp(2),
  paddingVertical: scale.hp(0.5),
  borderRadius: scale.hp(1.55),
},
statusText: {
  color: '#fff',
  fontSize: scale.hp(1.55),
  fontWeight: '600',
  textTransform: 'capitalize',
},
dateText: {
  fontSize: scale.hp(1.55),
  color: '#999',
},
orderBody: {
  marginBottom: scale.hp(2.1),
},
receiverInfo: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: "space-between",
  marginBottom: scale.hp(1.55),
},
receiverInfo1: {
  flexDirection: 'row',
  alignItems: 'center',
},
receiverText: {
  marginLeft: scale.wp(2),
  fontSize: scale.hp(2.1),
  color: '#333',
  fontWeight: '500',
},
amountInfo: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
},
amountText: {
  fontSize: scale.hp(2.35),
  fontWeight: 'bold',
  color: Colors.primary,
},
sourceText: {
  fontSize: scale.hp(1.8),
  color: '#666',
  textTransform: 'capitalize',
},
orderFooter: {
  borderTopWidth: 1,
  borderTopColor: '#eee',
  paddingTop: scale.hp(1.55),
},
actionButtons: {
  flexDirection: 'row',
  justifyContent: 'space-around',
},
actionButton: {
  alignItems: 'center',
  padding: scale.hp(1.05),
},
actionButtonText: {
  fontSize: scale.hp(1.55),
  color: '#666',
  marginTop: scale.hp(0.5),
},
emptyList: {
  flex: 1,
},
emptyState: {
  alignItems: 'center',
  justifyContent: 'center',
  padding: scale.hp(5.2),
},
emptyStateText: {
  fontSize: scale.hp(2.35),
  fontWeight: '600',
  color: '#666',
  marginTop: scale.hp(2.1),
  marginBottom: scale.hp(1.05),
},
emptyStateSubText: {
  fontSize: scale.hp(1.8),
  color: '#999',
  textAlign: 'center',
},
errorState: {
  alignItems: 'center',
  justifyContent: 'center',
  padding: scale.hp(5.2),
},
errorStateText: {
  fontSize: scale.hp(2.35),
  fontWeight: '600',
  color: '#f44336',
  marginTop: scale.hp(2.1),
  marginBottom: scale.hp(1.05),
},
errorStateSubText: {
  fontSize: scale.hp(1.8),
  color: '#666',
  textAlign: 'center',
  marginBottom: scale.hp(2.1),
},
retryButton: {
  backgroundColor: '#CD0202',
  paddingHorizontal: scale.wp(3.9),
  paddingVertical: scale.hp(1.55),
  borderRadius: scale.hp(1.05),
  marginTop: scale.hp(2.1),
  alignItems: 'center',
},
retryButtonText: {
  color: '#fff',
  fontWeight: '600',
},
modalOverlay: {
  flex: 1,
  backgroundColor: 'transparent',
},
modalBackdrop: {
  flex: 1,
  backgroundColor: "rgba(0,0,0,0.5)",
  justifyContent: "flex-end",
},
modalCard: {
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  backgroundColor: '#fff',
  borderTopLeftRadius: scale.hp(3.2),
  borderTopRightRadius: scale.hp(3.2),
  padding: scale.hp(2.1),
  elevation: 5,
  shadowColor: "#000",
  shadowOffset: { width: 0, height: -scale.hp(0.25) },
  shadowOpacity: 0.25,
  shadowRadius: scale.hp(0.5),
},
modalHeader: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: scale.hp(2.1),
  paddingBottom: scale.hp(1.55),
  borderBottomWidth: 1,
  borderBottomColor: "#F0F0F0",
},
modalTitle: {
  fontSize: scale.hp(2.35),
  fontWeight: "700",
  color: Colors.textPrimary,
},
closeButton: {
  padding: scale.hp(0.5),
},
filterOptions: {
  marginBottom: scale.hp(2.1),
},
filterSectionTitle: {
  fontSize: scale.hp(2.1),
  fontWeight: '600',
  color: '#333',
  marginBottom: scale.hp(1.55),
},
filterOption: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: scale.hp(1.55),
  borderBottomWidth: 1,
  borderBottomColor: '#f0f0f0',
},
filterOptionSelected: {
  backgroundColor: '#f0f7ff',
},
filterOptionText: {
  fontSize: scale.hp(2.1),
  color: '#333',
  textTransform: 'capitalize',
},
filterOptionTextSelected: {
  color: Colors.primary,
  fontWeight: '600',
},
modalActions: {
  flexDirection: 'row',
  gap: scale.hp(1.55),
},
 resetButton: {
  flex: 1,
  padding: scale.hp(1.55),
  alignItems: 'center',
  borderWidth: 1,
  borderColor: '#ddd',
  borderRadius: scale.hp(1.05),
},
resetButtonText: {
  color: '#666',
  fontWeight: '600',
},
applyButton: {
  flex: 1,
  padding: scale.hp(1.55),
  alignItems: 'center',
  backgroundColor: Colors.primary,
  borderRadius: scale.hp(1.05),
},
applyButtonText: {
  color: '#fff',
  fontWeight: '600',
},
orderDetails: {
  maxHeight: scale.hp(108.8),
},
receiptContainer: {
  backgroundColor: '#fff',
  padding: scale.hp(2.6),
  borderRadius: scale.hp(1.55),
  borderWidth: 1,
  borderColor: '#e0e0e0',
  marginBottom: scale.hp(2.6),
  width: "100%",
},
receiptHeader: {
  alignItems: 'center',
  marginBottom: scale.hp(1.95),
},
receiptTitle: {
  fontSize: scale.hp(2.85),
  fontWeight: 'bold',
  color: Colors.primary,
  marginBottom: scale.hp(0.65),
},
receiptSubtitle: {
  fontSize: scale.hp(1.8),
  color: '#666',
},
receiptDivider: {
  height: scale.hp(0.25),
  backgroundColor: Colors.primary,
  marginVertical: scale.hp(1.95),
},
receiptDividerThin: {
  height: scale.hp(0.13),
  backgroundColor: '#e0e0e0',
  marginVertical: scale.hp(1.3),
},
receiptDetails: {
  marginBottom: scale.hp(1.95),
},
receiptRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: scale.hp(1.3),
},
receiptLabel: {
  fontSize: scale.hp(1.8),
  color: '#666',
  fontWeight: '500',
},
receiptValue: {
  fontSize: scale.hp(1.8),
  color: '#333',
  fontWeight: '500',
},
receiptStatus: {
  paddingHorizontal: scale.wp(2.6),
  paddingVertical: scale.hp(0.5),
  borderRadius: scale.hp(1.55),
},
receiptStatusText: {
  color: '#fff',
  fontSize: scale.hp(1.55),
  fontWeight: '600',
  textTransform: 'capitalize',
},
receiptFooter: {
  alignItems: 'center',
},
thankYouText: {
  fontSize: scale.hp(2.1),
  fontWeight: '600',
  color: '#333',
  marginBottom: scale.hp(0.65),
},
supportText: {
  fontSize: scale.hp(1.55),
  color: '#666',
},
receiptButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  padding: scale.hp(1.55),
  borderRadius: scale.hp(1.05),
  flex: 1,
  marginHorizontal: scale.wp(1.3),
},
downloadButton: {
  backgroundColor: Colors.primary,
},
shareButton: {
  backgroundColor: '#4caf50',
},
receiptButtonText: {
  color: '#fff',
  fontWeight: '600',
  marginLeft: scale.wp(1.3),
},
skeletonOrderItem: {
  backgroundColor: '#fff',
  borderRadius: scale.hp(1.55),
  padding: scale.hp(2.1),
  marginBottom: scale.hp(2.1),
  shadowColor: '#000',
  shadowOffset: { width: 0, height: scale.hp(0.25) },
  shadowOpacity: 0.1,
  shadowRadius: scale.hp(0.5),
  elevation: 3,
  borderLeftWidth: 4,
  borderLeftColor: '#E0E0E0',
},
skeletonOrderHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: scale.hp(1.05),
},
skeletonTxnId: {
  width: scale.wp(31.2),
  height: scale.hp(1.8),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
},
skeletonStatus: {
  width: scale.wp(15.6),
  height: scale.hp(2.6),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(1.3),
},
skeletonDate: {
  width: scale.wp(20.8),
  height: scale.hp(1.55),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
  marginBottom: scale.hp(1.55),
},
skeletonOrderBody: {
  marginBottom: scale.hp(2.1),
},
skeletonReceiverInfo: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: scale.hp(1.55),
},
skeletonReceiverIcon: {
  width: scale.wp(4.2),
  height: scale.wp(4.2),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.wp(2.1),
  marginRight: scale.wp(2),
},
skeletonReceiverText: {
  width: scale.wp(26),
  height: scale.hp(2.1),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
},
skeletonAmountInfo: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
},
skeletonAmount: {
  width: scale.wp(20.8),
  height: scale.hp(2.35),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
},
skeletonSource: {
  width: scale.wp(15.6),
  height: scale.hp(1.8),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
},
skeletonOrderFooter: {
  borderTopWidth: 1,
  borderTopColor: '#eee',
  paddingTop: scale.hp(1.55),
},
skeletonActionButtons: {
  flexDirection: 'row',
  justifyContent: 'space-around',
},
skeletonActionButton: {
  width: scale.wp(15.6),
  height: scale.hp(3.9),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.8),
},
skeletonSearchContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#fff',
  margin: scale.hp(2.1),
  borderRadius: scale.hp(1.05),
  paddingHorizontal: scale.wp(2.9),
  borderWidth: 1,
  borderColor: '#ddd',
  height: scale.hp(5.7),
},
skeletonSearchIcon: {
  width: scale.wp(5.2),
  height: scale.wp(5.2),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.wp(2.6),
  marginRight: scale.wp(2),
},
skeletonSearchInput: {
  flex: 1,
  height: scale.hp(2.6),
  backgroundColor: '#E0E0E0',
  borderRadius: scale.hp(0.5),
},
});

export default OrderStyles;