import { Platform, StyleSheet, Dimensions } from "react-native";
import { Colors } from "../../../theme/colors";
import { scale } from "../../../utils/normalizeSize";

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const AVATAR_SIZE = 100;
const EDIT_SIZE = 32;

const ProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    paddingBottom: scale.hp(10.4),
  },
  scrollView: {
    flex: 1,
  },
  skeletonContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  skeletonHeader: {
    height: scale.hp(26),
    justifyContent: 'center',
    alignItems: 'center',
  },
  skeletonAvatarWrapper: {
    alignItems: 'center',
    position: 'relative',
  },
  skeletonAvatar: {
    width: scale.wp(26),
    height: scale.wp(26),
    borderRadius: scale.wp(13),
    backgroundColor: '#e0e0e0',
    marginBottom: scale.hp(1.3),
  },
  skeletonEditButton: {
    width: scale.wp(8.3),
    height: scale.wp(8.3),
    borderRadius: scale.wp(4.15),
    backgroundColor: '#e0e0e0',
    position: 'absolute',
    bottom: scale.hp(0.65),
    right: scale.wp(1.3),
  },
  skeletonFormContainer: {
    padding: scale.hp(3.1),
  },
  skeletonSectionTitle: {
    width: scale.wp(52),
    height: scale.hp(3.1),
    backgroundColor: '#e0e0e0',
    borderRadius: scale.hp(0.8),
    marginBottom: scale.hp(3.1),
  },
  skeletonInputGroup: {
    marginBottom: scale.hp(2.6),
  },
  skeletonLabel: {
    width: scale.wp(31.2),
    height: scale.hp(2.1),
    backgroundColor: '#e0e0e0',
    borderRadius: scale.hp(0.5),
    marginBottom: scale.hp(1.05),
  },
  skeletonInput: {
    width: '100%',
    height: scale.hp(6.5),
    backgroundColor: '#e0e0e0',
    borderRadius: scale.hp(1.55),
  },
  skeletonButton: {
    width: '100%',
    height: scale.hp(6.5),
    backgroundColor: '#e0e0e0',
    borderRadius: scale.hp(3.2),
    marginTop: scale.hp(3.1),
  },
  shimmerContainer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  shimmer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    transform: [{ skewX: '-20deg' }],
  },
  scrollContent: {
    flexGrow: 1,
    marginBottom: scale.hp(13),
  },
  header: {
    height: scale.hp(28.6),
    justifyContent: "center",
    alignItems: "center",
    paddingTop: Platform.OS === "android" ? scale.hp(3.9) : 0,
  },
  avatarContainer: {
    alignItems: "center",
  },
  avatarWrapper: {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: scale.hp(2),
  },
  avatar: {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    borderRadius: AVATAR_SIZE / 2,
    borderWidth: 3,
    borderColor: "#fff",
  },
  avatarPlaceholder: {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    borderRadius: AVATAR_SIZE / 2,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderWidth: 3,
    borderColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  editBtn: {
    position: "absolute",
    right: scale.wp(-1),
    bottom: scale.hp(-0.5),
    width: EDIT_SIZE,
    height: EDIT_SIZE,
    borderRadius: EDIT_SIZE / 2,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  userName: {
    color: "#fff",
    fontSize: scale.hp(2.85),
    fontWeight: "700",
    marginBottom: scale.hp(0.65),
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  userEmail: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: scale.hp(1.8),
    fontWeight: "500",
  },
  formContainer: {
    padding: scale.hp(2.6),
    marginTop: -scale.hp(2.6),
    backgroundColor: "#fff",
    borderTopLeftRadius: scale.hp(3.2),
    borderTopRightRadius: scale.hp(3.2),
    minHeight: scale.hp(90.5),
    zIndex: 1000,

    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: scale.hp(1.55),
    shadowOffset: { width: 0, height: -scale.hp(0.5) },
  },
  sectionTitle: {
    fontSize: scale.hp(2.6),
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: scale.hp(3.2),
    textAlign: "center",
  },
  inputGroup: {
    marginBottom: scale.hp(2.9),
  },
  label: {
    fontSize: scale.hp(2),
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: scale.hp(1.3),
    marginLeft: scale.wp(1.3),
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E8E8E8",
    borderRadius: scale.hp(1.55),
    backgroundColor: "#FAFAFA",
    paddingHorizontal: scale.wp(3.9),
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: scale.hp(0.4),
    shadowOffset: { width: 0, height: scale.hp(0.13) },
  },
  inputIcon: {
    marginRight: scale.wp(3.1),
  },
  input: {
    flex: 1,
    height: scale.hp(6.8),
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
    fontWeight: "500",
  },
  inputError: {
    borderColor: Colors.primary,
    backgroundColor: "#FFF5F5",
  },
  errorText: {
    color: Colors.primary,
    fontSize: scale.hp(1.7),
    marginTop: scale.hp(0.8),
    marginLeft: scale.wp(1.3),
    fontWeight: "500",
  },
  helpText: {
    color: "#8E8E93",
    fontSize: scale.hp(1.7),
    marginTop: scale.hp(0.8),
    marginLeft: scale.wp(1.3),
    fontStyle: "italic",
  },
  updateButton: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.primary,
    padding: scale.hp(2.3),
    borderRadius: scale.hp(1.8),
    marginTop: scale.hp(2),
    marginBottom: scale.hp(3.9),
    gap: scale.wp(3.1),
    elevation: 4,
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: scale.hp(0.8),
    shadowOffset: { width: 0, height: scale.hp(0.4) },
  },
  updateButtonDisabled: {
    opacity: 0.6,
  },
  updateButtonText: {
    color: "#fff",
    fontSize: scale.hp(2.2),
    fontWeight: "700",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  loadingText: {
    marginTop: scale.hp(1.3),
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  imagePickerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: scale.hp(3.2),
    borderTopRightRadius: scale.hp(3.2),
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: scale.hp(2.6),
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  pickerTitle: {
    fontSize: scale.hp(2.35),
    fontWeight: '700',
    color: '#000',
  },
  closeButton: {
    padding: scale.hp(0.5),
  },
  pickerOptions: {
    padding: scale.hp(2.6),
    paddingBottom: scale.hp(10),
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale.hp(2.1),
    paddingHorizontal: scale.wp(2.6),
  },
  optionIcon: {
    width: scale.wp(11.7),
    height: scale.wp(11.7),
    borderRadius: scale.hp(1.55),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale.wp(3.9),
  },
  optionText: {
    fontSize: scale.hp(2.1),
    fontWeight: '600',
    color: '#000',
  },
  cancelButton: {
    backgroundColor: '#F8F8F8',
    marginHorizontal: scale.wp(4.9),
    marginBottom: Platform.OS === 'ios' ? 0 : 0,
    paddingVertical: scale.hp(2.1),
    borderRadius: scale.hp(1.55),
    alignItems: 'center',
    marginTop: scale.hp(1.3),
  },
  cancelButtonText: {
    fontSize: scale.hp(2.1),
    fontWeight: '600',
    color: Colors.primary,
  },

  // Success Modal Styles
  successOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale.hp(2.6),
  },
  successContainer: {
    backgroundColor: '#fff',
    borderRadius: scale.hp(3.2),
    padding: scale.hp(3.9),
    alignItems: 'center',
    maxWidth: scale.wp(78),
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: scale.hp(1.3),
    shadowOffset: { width: 0, height: scale.hp(0.5) },
  },
  successIcon: {
    width: scale.wp(20.8),
    height: scale.wp(20.8),
    borderRadius: scale.wp(10.4),
    backgroundColor: '#CD0202',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale.hp(2.6),
  },
  successTitle: {
    fontSize: scale.hp(2.85),
    fontWeight: '700',
    color: '#000',
    marginBottom: scale.hp(1.3),
    textAlign: 'center',
  },
  successMessage: {
    fontSize: scale.hp(2.1),
    color: '#666',
    textAlign: 'center',
    lineHeight: scale.hp(2.9),
  },
});


export default ProfileStyles;