
import { StyleSheet } from 'react-native';
import { Colors } from "../../theme/colors";
import { scale } from '../../utils/normalizeSize';
const DataStyles = StyleSheet.create({
  sectionTitle: {
    fontSize: scale.hp(2.1),
    marginBottom: scale.hp(1.55),
    fontWeight: "600",
    color: Colors.textPrimary,
  },
  smallLabel: {
    fontSize: scale.hp(1.7),
    color: Colors.textPrimary,
    marginBottom: scale.hp(0.8),
    marginTop: scale.hp(1.55),
  },
  dropField: {
    height: scale.hp(8.4),
    borderRadius: scale.hp(6.5),
    marginBottom: scale.hp(1.95),
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: scale.wp(3.9),
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: scale.hp(1.05),
    marginBottom: scale.hp(1.55),
  },
  editLink: {
    color: Colors.primary,
    fontSize: scale.hp(2.1),
    fontWeight: "600",
  },
  phoneRow: {
    flexDirection: "row",
    height: scale.hp(8.4),
    borderRadius: scale.hp(6.5),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E6E6E6",
    backgroundColor: "#fff",
  },
  phonePrefix: {
    paddingHorizontal: scale.wp(3.9),
    flexDirection: "row",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#EEE",
    backgroundColor: "#FAFAFA",
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: scale.wp(3.9),
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
  },
  operatorPill: {
    alignSelf: "flex-start",
    paddingHorizontal: scale.wp(2.4),
    height: scale.hp(3.1),
    borderRadius: scale.hp(1.55),
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  countryBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.05),
    paddingHorizontal: scale.wp(3.9),
    backgroundColor: "#F5F5F5",
    borderRadius: scale.hp(2.6),
    alignSelf: "flex-start",
    marginBottom: scale.hp(2.1),
  },
  categoriesScroll: {
    marginBottom: scale.hp(2.1),
  },
  categoriesContainer: {
    flexDirection: "row",
    gap: scale.wp(1.95),
  },
  categoryChip: {
    paddingHorizontal: scale.wp(4.9),
    paddingVertical: scale.hp(1.55),
    borderRadius: scale.hp(3.2),
    backgroundColor: "#F5F5F5",
  },
  categoryChipActive: {
    backgroundColor: Colors.primary,
  },
  categoryText: {
    fontSize: scale.hp(1.8),
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  categoryTextActive: {
    color: Colors.white,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: scale.hp(6.5),
    paddingHorizontal: scale.wp(3.9),
    marginBottom: scale.hp(2.1),
    height: scale.hp(6.5),
  },
  searchIcon: {
    marginRight: scale.wp(1.95),
  },
  searchInput: {
    flex: 1,
    fontSize: scale.hp(2.1),
    color: Colors.textPrimary,
  },
  bundleCard: {
    borderRadius: scale.hp(2.1),
    borderWidth: 1,
    borderColor: "#E8E8E8",
    backgroundColor: "#fff",
    padding: scale.hp(2.1),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  bundleCardActive: {
    borderColor: Colors.primary,
    backgroundColor: "#FFF5F5",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  bundleHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: scale.hp(1.55),
  },
  operatorLogo: {
    width: scale.wp(9.75),
    height: scale.wp(9.75),
    borderRadius: scale.wp(4.9),
    marginRight: scale.wp(2.9),
  },
  bundleInfo: {
    flex: 1,
  },
  bundleName: {
    fontSize: scale.hp(2.1),
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: scale.hp(0.5),
  },
  bundleDesc: {
    fontSize: scale.hp(1.8),
    color: Colors.textSecondary,
    lineHeight: scale.hp(2.6),
  },
  bundleFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bundlePrice: {
    fontSize: scale.hp(2.35),
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  bundleSeparator: {
    height: scale.hp(1.55),
  },
  summaryCard: {
    marginTop: scale.hp(2.35),
    borderWidth: 1,
    borderColor: "#F2DAD7",
    backgroundColor: "#FFF",
    borderRadius: scale.hp(1.55),
    padding: scale.hp(2.1),
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: scale.hp(0.8),
  },
  summaryTotal: {
    borderTopWidth: 1,
    borderTopColor: "#F2F2F2",
    paddingTop: scale.hp(1.05),
    marginTop: scale.hp(0.5),
  },
  summaryKey: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.8),
  },
  summaryValue: {
    color: Colors.textPrimary,
    fontSize: scale.hp(1.8),
    textAlign: "right",
    flex: 1,
    paddingLeft: scale.wp(2),
  },
  successCircle: {
    width: scale.wp(23.4),
    height: scale.wp(23.4),
    borderRadius: scale.wp(11.7),
    backgroundColor: "rgba(76,175,80,0.1)",
    borderWidth: 2,
    borderColor: "rgba(76,175,80,0.35)",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: scale.hp(1.55),
  },
  successTitle: {
    fontSize: scale.hp(2.6),
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: scale.hp(2.1),
  },
  kv: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: scale.hp(0.8),
  },
  k: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.7),
  },
  v: {
    color: Colors.textPrimary,
    fontSize: scale.hp(1.7),
  },
  totalBox: {
    width: "100%",
    backgroundColor: "#F5F5F7",
    borderRadius: scale.hp(1.55),
    paddingVertical: scale.hp(1.8),
    alignItems: "center",
    marginVertical: scale.hp(2.35),
  },
  totalLabel: {
    color: Colors.textSecondary,
    fontSize: scale.hp(1.55),
  },
  totalValue: {
    color: Colors.textPrimary,
    fontSize: scale.hp(2.6),
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: scale.hp(3.2),
    borderTopRightRadius: scale.hp(3.2),
    padding: scale.hp(2.1),
    elevation: 5,
    shadowColor: "#000",
        shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scale.hp(2.1),
    paddingBottom: scale.hp(1.55),
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  modalTitle: {
    fontSize: scale.hp(2.35),
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  modalRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.55),
    paddingHorizontal: scale.wp(2),
  },
  closeButton: {
    padding: scale.hp(0.5),
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: scale.hp(5.2),
  },
  emptyText: {
    fontSize: scale.hp(2.1),
    color: "#999",
    marginTop: scale.hp(1.55),
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: scale.hp(1.55),
  },
  contactAvatar: {
    width: scale.wp(9.75),
    height: scale.wp(9.75),
    borderRadius: scale.wp(4.9),
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: scale.wp(2.9),
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: scale.hp(2.1),
    fontWeight: "500",
    color: Colors.textPrimary,
  },
  contactPhone: {
    fontSize: scale.hp(1.8),
    color: Colors.textSecondary,
    marginTop: scale.hp(0.25),
  },
  contactSeparator: {
    height: 1,
    backgroundColor: "#F0F0F0",
  },
  emptyProducts: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: scale.hp(5.2),
  },
  emptyProductsText: {
    fontSize: scale.hp(2.1),
    color: "#999",
    marginTop: scale.hp(1.55),
  },
});
export default DataStyles;